package com.sg.domaininterface.model.payableinvoice;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * One fee line — a {@code t_invoice_items} row, and the source of a UBL {@code InvoiceLine}.
 *
 * <p>Field-for-field with {@code InvoiceItemEntity} (com.sg.jpa.entity).
 *
 * <p><b>The e-invoicing path populates a minority of these fields.</b> An inbound UBL line
 * carries an amount, a currency, a quantity and a name; everything else here — the FX columns,
 * the trade columns, the market and agreement references — is filled in later by pricing and
 * reconciliation, or arrives on a manually captured invoice. They are modelled because the
 * column exists and a reader of this class should see the whole row, not the slice one pipeline
 * happens to write.
 *
 * <p><b>{@code itemDescription} is where the supplier's line label goes, and nowhere else.</b>
 * It used to be copied onto {@code feeType} as well, which turned arbitrary supplier free text
 * into a classification code. {@code feeType} is a taxonomy value owned by the fee referential.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceItem implements Serializable {

  private static final long serialVersionUID = 2L;

  /** Primary key. Generated by the mapper when it builds the line. */
  private UUID invoiceItemId;

  /** Correlates to {@code InvoicePayableModel.invoiceReference}. Set by the store. */
  private String invReferenceSg;

  private String feeType;
  private String groupingKey;
  private String natureOfExpense;
  private String accountNumber;
  private String product;

  private BigDecimal notionQuantity;
  private BigDecimal feeAmount;
  private String feeCurrency;

  private BigDecimal providerRate;
  private BigDecimal exchangedRate;
  private BigDecimal exchangedAmount;
  private String exchangedAmountCurrency;

  private BigDecimal vatAmount;
  private String vatAmountCurrency;

  private String debitCredit;

  private LocalDate itemsCreationDate;
  private String itemsCreationUser;
  private LocalDate itemsLastUpdateDate;
  private String itemsLastUpdateUser;

  /** The invoice line's own label. On the inbound path, the supplier's {@code Item.name}. */
  private String itemDescription;

  private String marketRegion;
  private String feeAgreement;
  private String business;

  /**
   * {@code tradedAmount} and {@code fxRate} are declared {@code String} on the entity despite
   * being numbers. Mirrored rather than corrected — the column is varchar either way, and a
   * {@code BigDecimal} here would only move the conversion, not remove it.
   */
  private String tradedCurrency;

  private String tradedAmount;
  private String fxRate;
}
