package com.sg.domaininterface.model.payableinvoice;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The {@code t_invoice_payable} envelope: an {@link InvoicePayable} payload plus the columns
 * hoisted out of it.
 *
 * <p>Field-for-field with {@code InvoicePayableEntity} (com.sg.jpa.entity), with two
 * deliberate omissions and one deliberate absence:
 *
 * <ul>
 *   <li><b>{@code corailResponse} and {@code paymentDetails} are not modelled.</b> Their types
 *       ({@code CorailResponse}, {@code PaymentDetailsForInvoice}) live in the SG domain and are
 *       not on this service's classpath. The columns exist and other producers write them; this
 *       service leaves them alone. Reconstructing those types from their names would produce
 *       something shaped like a guess and serialise like a bug.</li>
 *   <li><b>No {@code business} / {@code feeId} / {@code feeType} / lifecycle fields.</b> Those
 *       are e-invoicing's own columns (see {@code V3__einvoice_registration_columns.sql}) and
 *       travel on the persist request rather than the model, because they are decided by the
 *       registration pipeline and not by the mapping.</li>
 * </ul>
 *
 * <p><b>{@code invoiceReference} is null coming out of the mapper.</b> It is minted from
 * {@code seq_invoice_reference} at persist time. The incoming e-invoice's own id is the
 * supplier's reference and is unique only within that supplier; it lands on
 * {@link InvoicePayable#getProviderReference()} instead.
 *
 * <p><b>{@code id} is likewise null until persisted.</b> The store generates the UUID.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoicePayableModel implements Serializable {

  private static final long serialVersionUID = 2L;

  /** Primary key. Generated by the store, not by the mapper. */
  private UUID id;

  /** Minted from {@code seq_invoice_reference} at persist time. Null before that. */
  private String invoiceReference;

  private LocalDate invoiceDate;
  private String invoiceType;
  private String invoiceStatus;
  private String feeCategory;

  private String providerId;
  private String sgEntity;
  private String refCptyId;

  private LocalDate tradingStartDate;
  private LocalDate tradingEndDate;

  private BigDecimal amount;
  private String currency;

  private LocalDate createdDate;
  private LocalDate lastUpdatedDate;
  private String createdByUser;
  private String lastUpdatedByUser;

  /**
   * Declared {@code String} on the entity despite the name — mirrored rather than corrected,
   * because changing the type here would not change the column.
   */
  private String reAttachmentDate;

  private String assignedTo;
  private String ssiStatus;
  private String priority;

  /** Soft delete. A deleted row must not block re-registration — see the duplicate check. */
  private boolean isDeleted;

  private String assetClass;

  /** The producer discriminator: {@code EINVOICE} / {@code MANUAL} / {@code SGAI}. */
  private String invoiceFlow;

  private String reconProcess;

  /** The payload, stored whole in the {@code invoice_payable} jsonb column. */
  private InvoicePayable invoicePayable;
}
