-- Quarantine table: the system of record for referential data-quality defects and their corrections.
--
-- Portable across Postgres / Oracle / H2. One ACTIVE row per (key_space, lookup_key): soft-deleted
-- rows set active_flag to NULL, and NULL never collides in a unique index — so full history is
-- retained without depending on partial-index support, which Oracle lacks.
--
-- Adopting into your repo: move this file into your existing migration folder and renumber it to
-- follow your latest version.

CREATE TABLE party_registration_quarantine (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    key_space           VARCHAR(16)  NOT NULL,   -- SIREN | SIRET | BDR_ID
    lookup_key          VARCHAR(64)  NOT NULL,   -- already normalized by the domain
    active_flag         CHAR(1),                 -- 'Y' while live, NULL once retired

    -- Identity of "this exact defect": anomaly types plus a hash of the fields they concern.
    -- Unchanged fingerprint => same defect => stays silent. Changed => a genuinely different bad
    -- value => re-notify, and any correction written against the old value is discarded.
    anomaly_fingerprint VARCHAR(128) NOT NULL,
    anomaly_types       VARCHAR(512) NOT NULL,   -- comma-separated
    servability         VARCHAR(16)  NOT NULL,   -- SERVABLE | BLOCKING

    raw_payload         CLOB,                    -- NULL when the referential returned nothing
    corrected_payload   CLOB,                    -- operator-supplied; outranks the referential

    status              VARCHAR(16)  NOT NULL,   -- PENDING | CORRECTED | SOFT_DELETED

    detected_at         TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,   -- drives cross-instance cache eviction
    notified_at         TIMESTAMP,               -- NULL => nobody told yet; the notify-once gate

    corrected_by        VARCHAR(64),
    notes               VARCHAR(1024)
);

-- Enforces one live row per key while letting retired rows accumulate as history.
CREATE UNIQUE INDEX ux_prq_active ON party_registration_quarantine (key_space, lookup_key, active_flag);

-- The poller scans this on every interval across every instance. Keep it.
CREATE INDEX ix_prq_updated ON party_registration_quarantine (updated_at);

-- For the operator console: "what is pending, worst first".
CREATE INDEX ix_prq_status ON party_registration_quarantine (status, servability);
