-- ============================================================================
-- V2: the invoice-payable tables written by the e-invoice registration pipeline.
--
-- Three tables, deliberately NOT joined by foreign keys. They correlate on
-- invoice_reference, a value this service mints from a sequence. No FKs because
-- the three are written by different steps that must each be able to land (and
-- be corrected) independently: a registration that fails at the document stage
-- still leaves a payable row an operator can see, and a trade file that arrives
-- late can be attached without the payable row being re-written. A FK would turn
-- each of those into a transaction that has to succeed or vanish entirely.
--
-- The cost of that choice is that nothing stops an orphan. The scheduler and the
-- ops UI both filter on invoice_reference, and the indexes below exist to make
-- that filtering cheap rather than to enforce integrity.
--
-- Portable across Postgres / Oracle / H2, following V1: identity via
-- GENERATED BY DEFAULT AS IDENTITY, payloads as CLOB rather than a
-- dialect-specific JSON type (the JDBC layer serialises to a string).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- The invoice_reference every table correlates on.
--
-- Minted here rather than taken from the incoming e-invoice: the e-invoice's own
-- id is the SUPPLIER's reference and is only unique within that supplier. It is
-- stored as provider_reference below, which is what the duplicate check keys on.
-- ----------------------------------------------------------------------------
CREATE SEQUENCE seq_invoice_reference START WITH 1000000 INCREMENT BY 1;


-- ----------------------------------------------------------------------------
-- t_invoice_payable — the InvoicePayableModel envelope.
--
-- The nested InvoicePayable travels as JSON in invoice_payable_json. Everything
-- hoisted into its own column is there because something queries or indexes it:
-- provider_reference for the duplicate check, business/invoice_status for the
-- ops UI, the lifecycle columns for the scheduler.
-- ----------------------------------------------------------------------------
CREATE TABLE t_invoice_payable (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Minted from seq_invoice_reference. The correlation key for the two tables
    -- below; unique here because this table is where it originates.
    invoice_reference        VARCHAR(64)  NOT NULL,

    -- The incoming e-invoice's own id (Invoice.id). Unique per supplier, not
    -- globally — which is exactly why it is not the correlation key.
    provider_reference       VARCHAR(64),

    business                 VARCHAR(16),                     -- MARK / SGSS / GTPS / GLBA / NULL
    feetype                  VARCHAR(64),                     -- canonical when the matcher resolved it
    fee_id                   VARCHAR(64),
    sg_entity                VARCHAR(32),
    provider_id              VARCHAR(32),

    invoice_status           VARCHAR(16)  NOT NULL,           -- REGISTERED / CANCELLED / INCOMPLETE
    comment                  VARCHAR(1024),

    -- The InvoicePayable payload. A JSON column rather than ~100 hoisted columns:
    -- InvoicePayable grows a field most quarters, and none of the fields not
    -- listed above are queried.
    invoice_payable_json     CLOB         NOT NULL,

    -- Every MappingError captured during registration, as JSON.
    error_codes              CLOB,

    lifecycle_event_type     VARCHAR(16),                     -- REFUSED / SUSPENDED / NULL
    lifecycle_reason_code    VARCHAR(32),                     -- DOUBLON / NON_CONFORME / JUSTIF_ABS / ...
    lifecycle_event_status   VARCHAR(16),                     -- PENDING / SENT / FAILED / NULL
    lifecycle_payload        CLOB,

    source                   VARCHAR(16)  NOT NULL,           -- EINVOICE only, for now

    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL,

    CONSTRAINT ck_pm_invoice_status
        CHECK (invoice_status IN ('REGISTERED', 'CANCELLED', 'INCOMPLETE')),
    CONSTRAINT ck_pm_lifecycle_event_type
        CHECK (lifecycle_event_type IS NULL
               OR lifecycle_event_type IN ('REFUSED', 'SUSPENDED')),
    CONSTRAINT ck_pm_lifecycle_event_status
        CHECK (lifecycle_event_status IS NULL
               OR lifecycle_event_status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT ck_pm_source
        CHECK (source IN ('EINVOICE'))
);

-- invoice_reference originates here, so it is unique here — and only here.
CREATE UNIQUE INDEX ux_pm_invoice_reference ON t_invoice_payable (invoice_reference);

-- The duplicate check: WHERE provider_reference = ? AND invoice_status = 'REGISTERED'.
CREATE INDEX ix_pm_provider_ref_status ON t_invoice_payable (provider_reference, invoice_status);

-- The scheduler drains PENDING lifecycle events oldest-first.
CREATE INDEX ix_pm_lifecycle_pending ON t_invoice_payable (lifecycle_event_status, created_at);

-- The ops UI filters by business and status.
CREATE INDEX ix_pm_business_status ON t_invoice_payable (business, invoice_status);


-- ----------------------------------------------------------------------------
-- t_invoice_item — one row per invoice line.
--
-- Correlated by invoice_reference, not by a FK to t_invoice_payable.id. Lines can
-- be added to an INCOMPLETE invoice later by a user, which is the whole reason
-- INCOMPLETE exists as a status.
-- ----------------------------------------------------------------------------
CREATE TABLE t_invoice_item (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_reference   VARCHAR(64)   NOT NULL,   -- correlates to t_invoice_payable
    invoice_item_id     VARCHAR(64),              -- the mapper's own UUID for the line

    -- The e-invoice line's Item.name lands here. It is the human-facing label a
    -- user reads on the line; fee_type is a classification code and is left for
    -- the fee taxonomy to populate, not for the supplier's free text.
    description         VARCHAR(512),

    fee_type            VARCHAR(64),
    fee_amount          DECIMAL(19, 4),
    fee_currency        VARCHAR(3),
    notion_quantity     DECIMAL(19, 4),
    grouping_key        VARCHAR(64),
    nature_of_expense   VARCHAR(64),

    created_at          TIMESTAMP     NOT NULL,
    updated_at          TIMESTAMP     NOT NULL
);

CREATE INDEX ix_ii_invoice_reference ON t_invoice_item (invoice_reference);


-- ----------------------------------------------------------------------------
-- t_invoice_documents — one row per attachment.
--
-- Holds the metadata plus the bytes. Correlated by invoice_reference for the
-- same reason as the items: an attachment may arrive after the payable row, and
-- a suspended invoice is unsuspended precisely by supplying one.
--
-- content is nullable so a row can record that a document was EXPECTED and is
-- missing — which is what a SUSPENDED lifecycle event is about.
-- ----------------------------------------------------------------------------
CREATE TABLE t_invoice_documents (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_reference   VARCHAR(64)   NOT NULL,   -- correlates to t_invoice_payable

    filename            VARCHAR(256),
    mime_type           VARCHAR(128),
    document_type       VARCHAR(32),              -- PDF / TRADE_FILE / OTHER
    -- Which side of the request carried it. Worth recording: "no attachment"
    -- reads very differently depending on whether the sender embedded nothing or
    -- the upload failed.
    source_channel      VARCHAR(16),              -- EINVOICE_BODY / MULTIPART
    size_bytes          BIGINT,
    content             BLOB,

    created_at          TIMESTAMP     NOT NULL,

    CONSTRAINT ck_id_source_channel
        CHECK (source_channel IS NULL
               OR source_channel IN ('EINVOICE_BODY', 'MULTIPART'))
);

CREATE INDEX ix_id_invoice_reference ON t_invoice_documents (invoice_reference);
