-- ============================================================================
-- V2: t_invoice_payable — landing table for e-invoice registrations.
--
-- Every incoming e-invoice registration writes exactly one row here — REGISTERED
-- when the mapping + all validation rules pass, CANCELLED when a failure fires,
-- INCOMPLETE when the only failure is EMPTY_LINE_ITEMS (users complete the invoice
-- in-app). The row is the durable record; email alerts are notification only.
--
-- Portable across Postgres / Oracle / H2. Same design principles as
-- V1__party_registration_quarantine.sql: identity uses GENERATED BY DEFAULT AS
-- IDENTITY (which all three dialects understand), JSONB payloads store as CLOB
-- on Oracle / TEXT on H2 via the JDBC layer's string codec (no dialect-specific
-- JSON types in the DDL).
--
-- Adopting into your repo: move this file into your existing migration folder
-- and renumber it to follow your latest version. Two indexes and one enum-like
-- CHECK constraint are load-bearing — see notes below.
-- ============================================================================

CREATE TABLE t_invoice_payable (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identity / lookup keys. invoice_reference is what humans quote; provider_reference is
    -- what the DuplicateInvoiceRule keys on (they mirror each other for e-invoice registrations
    -- but keeping both columns leaves future non-e-invoice sources their own key surface).
    invoice_reference        VARCHAR(64)  NOT NULL,
    provider_reference       VARCHAR(64),

    -- Marker-derived facets. business is enum-shaped; feetype comes from the FeeTypeMatcher's
    -- canonical output when it resolved, else the raw marker fee-type tail when it didn't.
    business                 VARCHAR(16),                     -- MARK / SGSS / GTPS / GLBA / NULL
    feetype                  VARCHAR(64),                     -- canonical when resolved
    fee_id                   VARCHAR(64),                     -- referential id when resolved
    sg_entity                VARCHAR(32),                     -- SIREN from marker
    provider_id              VARCHAR(32),

    -- Status + free-text comment (the winning MappingError#detail).
    invoice_status           VARCHAR(16)  NOT NULL,           -- REGISTERED / CANCELLED / INCOMPLETE
    comment                  VARCHAR(1024),

    -- Payload. Full InvoicePayableModel + line items serialised as JSON so we don't have to
    -- CREATE COLUMN every time InvoicePayable grows a field. The hoisted columns above cover
    -- everything the ops UI + duplicate check need.
    invoice_payable_json     CLOB         NOT NULL,
    items_json               CLOB,

    -- Every failure captured. Same JSON representation the alert email lists — one row per
    -- MappingError with code, description, detail, lifecycle mapping, cause message.
    error_codes              CLOB,

    -- Lifecycle-event columns. Populated only when the outcome has a non-null lifecycleEvent
    -- (i.e. REFUSED or SUSPENDED). A future scheduler polls WHERE lifecycle_event_status =
    -- 'PENDING' and posts the event back to e-invoice-service.
    lifecycle_event_type     VARCHAR(16),                     -- REFUSED / SUSPENDED / NULL
    lifecycle_reason_code    VARCHAR(32),                     -- DOUBLON / NON_CONFORME / JUSTIF_ABS / SIRET_ERR / ...
    lifecycle_event_status   VARCHAR(16),                     -- PENDING / SENT / FAILED / NULL
    lifecycle_payload        CLOB,                            -- serialised event body (built by publisher)

    -- Provenance. Hard-coded EINVOICE for this pipeline; other sources (MANUAL, SGAI) will
    -- reuse the table but bypass the registration pipeline entirely.
    source                   VARCHAR(16)  NOT NULL,

    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL,

    -- Enum-like domain checks. These match the constants in InvoiceRegistrationService and
    -- RegistrationOutcome.Status / LifecycleEventType. Adding a new value in code without
    -- updating this constraint is caught at insert time.
    CONSTRAINT ck_invoice_status
        CHECK (invoice_status IN ('REGISTERED', 'CANCELLED', 'INCOMPLETE')),
    CONSTRAINT ck_lifecycle_event_type
        CHECK (lifecycle_event_type IS NULL
               OR lifecycle_event_type IN ('REFUSED', 'SUSPENDED')),
    CONSTRAINT ck_lifecycle_event_status
        CHECK (lifecycle_event_status IS NULL
               OR lifecycle_event_status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT ck_source
        CHECK (source IN ('EINVOICE'))                        -- extend as new sources land
);

-- Duplicate check (spec rule 1) does WHERE provider_reference = ? AND invoice_status =
-- 'REGISTERED'. A partial index would be ideal but Oracle can't do them portably; a plain
-- composite covers the same query pattern at the cost of a slightly wider index.
CREATE INDEX ix_ip_provider_ref_status
    ON t_invoice_payable (provider_reference, invoice_status);

-- Scheduler polls PENDING lifecycle rows in FIFO order.
CREATE INDEX ix_ip_lifecycle_pending
    ON t_invoice_payable (lifecycle_event_status, created_at);

-- Ops UI filters by business + status.
CREATE INDEX ix_ip_business_status
    ON t_invoice_payable (business, invoice_status);
