package com.example.invoice.service.domain.model.payableinvoice;

import com.example.invoice.service.domain.model.invoice.ExtractedAttachment;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * One document attached to an invoice — a {@code t_invoice_document_payable} row.
 *
 * <p>Field-for-field with {@code InvoiceDocumentPayableEntity} (com.sg.jpa.entity).
 *
 * <p><b>Metadata only. There are no bytes on this class, by design.</b> Content lives in SGDoc;
 * {@link #getSgDocId()} is the handle the upload returns and the only route back to it. Holding
 * a second copy alongside the metadata would mean two things to keep in step, and the copy that
 * goes stale is always the one that is not the system of record.
 *
 * <p>{@code sgDocId} is null until the upload has happened. A row with a null handle is not a
 * broken row — it is the honest record that a document arrived and its content is not yet
 * retrievable. That distinction matters to the attachment rules: "no document was sent" and
 * "the document was sent but the upload failed" are different failures and get different
 * lifecycle events.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceDocumentPayable implements Serializable {

  private static final long serialVersionUID = 1L;

  /** Primary key. Generated by the store. */
  private UUID id;

  /** Correlates to {@code InvoicePayableModel.invoiceReference}. Set by the store. */
  private String invoiceReference;

  /** SGDoc's handle for the content. Null until the upload succeeds. */
  private String sgDocId;

  private String documentName;

  /** PDF / TRADE_FILE / OTHER — what the document is, for the rules' benefit. */
  private String documentType;

  /** The MIME type as declared by the sender. */
  private String format;

  /** Which channel delivered it: {@code EINVOICE_BODY} or {@code MULTIPART}. */
  private String incomingLine;

  private String senderAddress;
  private String arrivalTime;

  private String documentReference;
  private String documentStatus;

  private Boolean registrationStatus;
  private String registrationType;

  private String subject;
  private String body;
  private String comment;

  /** Maps to the entity's {@code created_by} column. */
  private String actionPerformedBy;

  private boolean isDeleted;

  private LocalDateTime createdDate;
  private LocalDateTime lastUpdatedDate;
  private String lastUpdatedByUser;

  private String parserId;
  private String parserResponse;
  private String parserSource;

  /**
   * Describe a received file, without its content.
   *
   * <p>The bytes are dropped here on purpose — they go to SGDoc, and {@code sgDocId} stays null
   * until that upload returns a handle. What is kept is everything needed to say what arrived
   * and to decide whether the rules are satisfied by it.
   *
   * @param attachment  the received file
   * @param incomingLine which channel delivered it, recorded so a later reader can tell an
   *                     upload apart from a copy embedded in the document
   */
  public static InvoiceDocumentPayable fromAttachment(ExtractedAttachment attachment,
                                                      String incomingLine) {
    return InvoiceDocumentPayable.builder()
        .documentName(attachment.filename())
        .documentType(classify(attachment.filename()))
        .format(attachment.mimeType())
        .incomingLine(incomingLine)
        .build();
  }

  /**
   * What kind of document this is, from its extension.
   *
   * <p>The extension is the sender's claim, not a verified fact — the magic-byte check during
   * extraction is what actually validates the content. This classification exists so the
   * trade-file rule's verdict is legible after the fact, which is why an unrecognised extension
   * is {@code OTHER} rather than an error: the rules decide what is missing, not this method.
   */
  static String classify(String filename) {
    if (filename == null) {
      return "OTHER";
    }
    String lower = filename.toLowerCase(Locale.ROOT);
    if (lower.endsWith(".pdf")) {
      return "PDF";
    }
    if (lower.endsWith(".csv") || lower.endsWith(".xlsx") || lower.endsWith(".xls")) {
      return "TRADE_FILE";
    }
    return "OTHER";
  }
}
